### ISSUE TITLE
运行gs_ver_code.py报错，安装chromedriver总是错误

### ISSUE THREAD

**Issue by ZhuningS** [jiaoht/python_util#2]
`
$ python gs_ver_code.py
gs_ver_code.py:19: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=opt)
Traceback (most recent call last):
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gs_ver_code.py", line 19, in <module>
    driver = webdriver.Chrome(chrome_options=opt)
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Intel\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

`

**Comment by jiaohongtao** [comment]
这个是一个本地驱动，不是python的依赖，你看下这个链接 https://jingyan.baidu.com/article/f7ff0bfcdd89ed2e27bb1379.html
